import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/layout/ThemeProvider";
import { headers } from "next/headers";
import TansactProvider from "@/components/layout/TansactProvider";
import { RouteProgress } from "@/components/route-progress";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Toaster } from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico", // /public path
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headerList = await headers();
    const pathname = headerList.get("x-current-path");
    // console.log("Root layout pathname", pathname);
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <head>
                <link rel="icon" href="/favicon.ico" sizes="any" />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} theme-surface antialiased`}
            >
                {/* next-theme - dark and light mode*/}
                <ThemeProvider
                    attribute="class" // 💡 This tells next-themes to apply 'dark' as a CSS class
                    defaultTheme="system"
                    // defaultTheme="system" // 💡 Default to system preference
                    enableSystem
                >
                    <TansactProvider>
                        <Toaster />
                        <RouteProgress />
                        <Header />
                        <main className="min-h-screen overflow-y-auto">
                            {children}
                        </main>
                        <Footer />
                    </TansactProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
